makefile.cargo
Utilize ARM and NEON optimizations (except for SkUtils, which would pull in
32-bit ARM assembly files not fit for AArch64)
=> Add AArch64 support

Cargo.toml, lib.rs, makefile.cargo, src/lib.rs, src/skia-c.cpp, src/skia-c.h, src/skia.rs
We would like to use Skia independently of rust-azure in Servo.
=> Move Skia / rust interface from rust-azure

makefile.cargo, src/lib.rs, src/linkhack.rs
When building the test harness we need to ensure that libraries are
properly linked and we avoid duplicate symbols.
=> Fixes for standalone builds

src/gl_rasterization_context.rs, src/gl_rasterization_context_android.rs, src/gl_rasterization_context_cgl.rs, src/gl_rasterization_context_glx.rs, src/skia-c.cpp, src/skia-c.h, src/skia.rs
When rust-azure uses GrContext, it needs a non-const pointer. This
allows it to stop trying to cast away the constness.
=> Deconstify GrContext

.travis.yml
This is a temporary work-around for an incompatibility between the
latest version of aster and the current rust nightly.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/62)
=> Pin travis to the 2015-07-10 rust nightly

src/gl_context.rs, src/gl_context_android.rs, src/gl_context_cgl.rs, src/gl_context_glx.rs, src/gl_rasterization_context.rs, src/gl_rasterization_context_android.rs, src/gl_rasterization_context_cgl.rs, src/gl_rasterization_context_glx.rs, src/lib.rs
This will allow Servo to preserve the same GLContext and GrContext
between rasterization targets, thus vastly improving the performance of
OpenGL rasterization.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/60)
=> Split out GLContext from GLRasterizationContext

.travis.yml, src/gl_context.rs, src/gl_context_cgl.rs, src/gl_context_glx.rs, src/gl_rasterization_context.rs, src/gl_rasterization_context_cgl.rs, src/gl_rasterization_context_glx.rs
Reuse the same framebuffer when creating GLRasterizationContexts. This
leads to another large overhead decrease, but means that we can only
create one GLRasterizationContext at a time.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/63)
=> Preserve framebuffers between GLRasterizationContexts

makefile.cargo
r? @metajack @glennw 
The missing encoder symbol definition was breaking android load while I've been switching our linker invocation ever-so-slightly.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/67)
=> Add missing encoder to makefile.cargo

makefile.cargo
* Added SKIA_OPTS_CXX_SRC_AARCH64 with sources that are non-A32
specific. (For most of the sources, the _opts_arm version is used
to utilize optimizations, but for SkUtils, the _opts_none version
is used, because the arm variant would pull in 32-bit ARM
assembly files not fit for AArch64.)
* Removed %_neon.o make rule, because it contained the -mfpu=neon
compiler option, which is not accepted by the AArch64 compiler.
The -mfpu=neon is added to the ARM-specific compiler flags
directly.
* As a side effect, since the ARM target seems to expect Neon now,
the unused SKIA_OPTS_CXX_SRC_ARM source list got removed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/69)
=> Separate AArch64 source list from ARM (& NEON) source list in makefile.cargo

Cargo.toml
Having servo fetch skia from crates.io would help with issues like #7687, as the compressed crate is 12 MB rather than 330 MB of git history. It’s still over the 10 MB limit of crates.io, though.
This excludes some of the repository’s directory from the archive created by `cargo package` to bring it to 5 MB, while the "Verifying" phase (running `cargo build` from sources extracted again from the archive)
still succeeds.
Before we can publish skia we still need to publish all the recursive dependencies.
r? @mrobinson
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/73)
=> Exclude a bunch of things from `cargo package`.

makefile.cargo
Checking for "eabi" in $TARGET causes failure to build natively on ARM systems.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/75)
=> Only set target-specific CC, CXX, and AR for cross-compile

makefile.cargo
this contains undefined symbol references and is never used
ref servo #8883
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/84)
=> remove SkBitmapHasher.cpp from build

Cargo.toml
expat-sys 2.1.0 is broken.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/87)
=> Bump expat-sys

Cargo.toml
This doesn’t significantly affect the size of tarballs, but make them not include some files with very long paths like
```
gm/rebaseline_server/testdata/outputs/expected/compare_rendered_pictures_test.CompareRenderedPicturesTest.test_endToEnd/compare_rendered_pictures.json
```
This will hopefully help on Windows:
http://logs.glob.uno/?c=mozilla%23servo#c403696
https://i.imgur.com/JeBRLlE.png
https://github.com/rust-lang/cargo/issues/2516
http://logs.glob.uno/?c=mozilla%23servo#c403699
The longest path from the crate root is now 65, down from 150.
```
third_party/freetype/include_overrides/freetype/config/ftoption.h
```
I’ve checked that `cargo build --target arm-linux-androideabi` still succeeds when run on the result of extracting the tarball.
r? @mbrubeck
---
This change is [<img …
=> Exclude more directories in Cargo.toml

Cargo.toml
This is related to [this servo issue](https://github.com/servo/servo/issues/11813) to update euclid on servo's dependencies.
I tried to [updating it on rust-azure](https://github.com/servo/rust-azure/pull/229), but I got a build problem related to skia.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/98)
=> Update euclid dependency

CMakeLists.txt, Cargo.toml
We don't want FreeType on Windows with MSVC, so don't try pulling it in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/104)
=> Don't use FreeType on Windows MSVC

Cargo.toml
The version number bump got lost in the merge, thus making it impossible for rust-azure to pick up a proper version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/106)
=> Really bump version number

CMakeLists.txt, Cargo.toml
Fixes:
- Linker error on Servo using `armv7-linux-androideabi` target
- Compilation error on Servo using `aarch64-linux-android` target
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/136)
=> Support armv7-linux-androideabi && aarch64-linux-android targets

Cargo.toml
See https://github.com/servo/rust-glx/pull/17 and servo/gleam#130. We also need this to avoid duplicated versions tidy check failures in order to land the new gleam version in Servo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/145)
=> Update glx dependency to 0.2

Cargo.toml, src/gl_context_wgl.rs
Skia doesn't build on Windows anymore.
PR tested on Windows this time.
Also, I'm surprised we don't run tests on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/150)
=> fix build errors on windows

Cargo.toml, src/gl_context_wgl.rs
Servo is not fully ready to use upstream glutin. And the new dependency on glutin upstream in skia is blocking further skia updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/151)
=> Revert the migration to upstream glutin for now.

CMakeLists.txt, Cargo.toml
Some distros like fedora auto-opt-in to ccache already if installed by putting
symlinks in $PATH (so `clang` points to `/usr/lib64/ccache/clang`).
This uses the same approach as mozjs and others to avoid calling ccache
recursively.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/176)
=> build: Don't auto opt-in to ccache.
