servo/skia

Cargo.toml, build.rs, makefile.cargo
Part of servo/servo#6088.  Depends on servo/libexpat#4 and servo/libfreetype2#9.  r? @SimonSapin
=> Use Cargo metadata to find include directories

makefile.cargo
Please consider merging this as it was required to compile servo on raspberry pi.
=> Porting to raspberry pi2.

Cargo.toml, makefile.cargo
=> Add ARM cross compile support,

Cargo.toml
Required for servo/servo#3369.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/57)
=> Switch to PistonDevelopers freetype-sys

Cargo.toml
This reverts commit 0123649224e4a8f55df54ab23b9f055018772cc1.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/58)
=> Revert "Switch to PistonDevelopers freetype-sys"

build.rs, makefile.cargo
This fixes cross compilation issues, so Skia now builds correctly for both Android and ARM.
(See servo/servo#6537)
Part of servo/servo#6327.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/64)
=> Fix cross compilation issues

build.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/65)
=> Use NUM_JOBS to control make -j

makefile.cargo
These were previously not compiled in.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/66)
=> Enable NEON optimizations

makefile.cargo
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/79)
=> Slightly more intelligent ARM FP build configuration

Cargo.toml
CC https://github.com/servo/servo/pull/8446
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/81)
=> Upgrade libc to 0.2

.gitignore, Cargo.toml, build.rs, makefile.cargo, src/core/SkAdvancedTypefaceMetrics.cpp, src/core/SkTraceEvent.h, src/gl_context.rs, src/gl_context_wgl.rs, src/gl_rasterization_context.rs, src/gl_rasterization_context_wgl.rs, src/lib.rs, src/ports/SkFontHost_FreeType.cpp, src/utils/win/SkWGL_win.cpp
This rebases and adds a final fix required for the win32 support authored by @vvuk originally in #74.
r? @Manishearth (for just my simple Cargo.toml update - rest has been reviewed)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/82)
=> Win32 support

Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/skia/85)
=> Bump gleam version

Cargo.toml
I should have done that in the armv7 PR, sorry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/93)
=> Bump version number to get armv7 picked up by servo

makefile.cargo
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/94)
=> Use ccache with CCACHE env variable is set

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/95)
=> Bump version to 0.20130412.9

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/96)
=> Simplify TOML syntax

CMakeLists.txt, Cargo.toml, build.rs, src/lib.rs
This switches the build to cmake on all platforms.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/97)
=> [msvc] Build skia using CMake for msvc compat

.travis.yml, CMakeLists.txt, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/102)
=> Use Travis on OS X

.travis.yml
It's not supposed to be used on this platform.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/103)
=> Don't install freetype on OS X

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/105)
=> Allow euclid 0.8

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/108)
=> Require io-surface 0.3.0 and bump the version

.travis.yml, Cargo.toml, src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/107)
=> Depend on servo-fontconfig-sys properly

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/110)
=> Bump to 0.20130412.17

CMakeLists.txt, Cargo.toml
SKIA_OPTS_ARM_SRC doesn't exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/111)
=> Properly set sources for arm32

CMakeLists.txt, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/112)
=> Explicitly require support for CXX and ASM

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/115)
=> Update glutin to 0.5

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/117)
=> Update euclid to 0.10 and io-surface to 0.5

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/118)
=> Properly update io-surface to 0.5.0

CMakeLists.txt, Cargo.toml, src/lib.rs
r? @vvuk or @larsbergstrom
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/123)
=> Use DirectWrite on Windows GNU

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/124)
=> Update glutin version.

Cargo.toml
Fixes #127.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/126)
=> Make glutin a Windows-only dependency

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/128)
=> Bump to 0.30000000.0

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/129)
=> Update to io-surface 0.6

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/125)
=> Update euclid to 0.11

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/130)
=> Update servo-glutin to 0.9

Cargo.toml, src/gl_context.rs, src/gl_context_android.rs, src/gl_context_cgl.rs, src/gl_context_glx.rs, src/gl_context_wgl.rs, src/gl_rasterization_context.rs, src/gl_rasterization_context_android.rs, src/gl_rasterization_context_cgl.rs, src/gl_rasterization_context_glx.rs, src/gl_rasterization_context_wgl.rs
It fixes  #131.
cc @glennw, @kvark
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/132)
=> Update gleam to v0.4

Cargo.toml, src/gl_context_android.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/133)
=> Fix android compilation error due to missing import.

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/137)
=> Allow euclid 0.13

Cargo.toml, src/gl_context.rs, src/gl_context_android.rs, src/gl_context_cgl.rs, src/gl_context_glx.rs, src/gl_context_wgl.rs, src/gl_rasterization_context.rs, src/gl_rasterization_context_android.rs, src/gl_rasterization_context_cgl.rs, src/gl_rasterization_context_glx.rs, src/gl_rasterization_context_wgl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/138)
=> Bump euclid to 0.14.

.travis.yml, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/139)
=> Update euclid and servo-glutin

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/140)
=> Use updated expat.

README
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/142)
=> Word transposition

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/146)
=> Update servo-glutin to 0.13

Cargo.toml
This is necessary for https://github.com/servo/servo/pull/19895
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/149)
=> use upstream glutin

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/152)
=> Update euclid to 0.17 and bump version

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/153)
=> Update glutin dependency.

Cargo.toml
Follow-up of https://github.com/servo/servo/pull/21087
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/158)
=> Update glutin to 0.17

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/160)
=> Update io-surface and bump version

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/161)
=> Update euclid and bump version

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/162)
=> Update gleam to 0.6

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/172)
=> Glutin 0.21

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/174)
=> Bump version to 0.30000021.0

Cargo.toml, src/gl_context_wgl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/175)
=> Use new Glutin context API on Windows

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/skia/179)
=> Update gleam, cgl, and io-surface. Publish 0.30000023.0.
